# Generated by Django 4.2.3 on 2023-08-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0002_product_on_sale_alter_amount_of_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amount_of_product',
            unique_together={('stock', 'product')},
        ),
    ]
