# Generated by Django 5.0.1 on 2024-02-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0006_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount_of_product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
        migrations.AddField(
            model_name='amount_of_product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='amount_of_product',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
