# Generated by Django 5.0.1 on 2024-02-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0007_remove_amount_of_product_amount_remove_product_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
