# Generated by Django 5.0.1 on 2024-02-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='owner',
            new_name='user',
        ),
    ]
