# Generated by Django 5.0.1 on 2024-02-29 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0012_delete_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stocks.cart')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stocks.store')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stocks.product')),
            ],
        ),
    ]
